version: '3.8'

services:

  # ===============================
  # 📦 Laravel backend (PHP + Composer)
  # ===============================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    ports:
      - "8000:8000"  # Laravel Vite dev server or Laravel's artisan serve
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: medical-system
      DB_USERNAME: root
      DB_PASSWORD: root

  # ===============================
  # ⚙️ Vue frontend (npm + vite)
  # ===============================
  frontend:
    image: node:20
    container_name: vue-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173" # Vite default port
    command: >
      sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true

  # ===============================
  # 🐬 MySQL Database
  # ===============================
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medical-system
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # ===============================
  # 🛠 Optional: phpMyAdmin
  # ===============================
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql-data:
